version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set up environment
          command: |
            source .circleci/pre_build.sh && get_env_vars
      - doctl/install
      - doctl/initialize:
          digitalocean-access-token: ${API_TOKEN}
      - run:
          name: Push Docker image to DigitalOcean Container Registry
          command: |
            doctl registry login --
            docker build -t registry.digitalocean.com/clockwork-registry/shareit:${CIRCLE_SHA1} .
            #docker push registry.digitalocean.com/clockwork-registry/shareit:${CIRCLE_SHA1}
  deploy:
    machine:
      image: default
    steps:
      - run:
          name: Deploy with Helm
          command: |
            helm upgrade --install shareit ./helm-template \
                --values ./.kubernetes/helm-values-${env}.yaml \
                --set image.tag=${CIRCLE_SHA1} 

workflows:
  shareit-pipeline:
    jobs:
      - build:
          context: docker_secrets
      # - deploy:
      #     requires:
      #       - build


          
