version: 2.1

jobs:
  build-and-deploy:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: Set up environment
          command: |
            source .circleci/pre_build.sh && get_env_vars
            source .circleci/pre_build.sh && set_up_environment
      - run:
          name: Build and push Docker image to DigitalOcean Container Registry
          command: |
            doctl auth init -t ${DO_TOKEN}
            doctl registry login -t ${DO_TOKEN}
            docker build -t registry.digitalocean.com/clockwork-registry/shareit:${CIRCLE_SHA1} .
            docker push registry.digitalocean.com/clockwork-registry/shareit:${CIRCLE_SHA1}
      - run:
          name: Deploy with Helm
          command: |
            doctl kubernetes cluster kubeconfig save cluster-1
            helm upgrade --install shareit ./helm-template \
                --values ./.kubernetes/helm-values-${env}.yaml \
                --set image.tag=${CIRCLE_SHA1} 

workflows:
  shareit-pipeline:
    jobs:
      - build-and-deploy:
          context: do_context


          
