image:
  repository: registry.digitalocean.com/clockwork-registry/shareit
  tag: 7795e9aab97ddc65c661863ee7b45a25a463fba2

ingress:
  host: shareit.do-interview.cw.substance3d.io

livenessProbe:
  path: "/healthz"
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  path: "/healthz"
  initialDelaySeconds: 5
  periodSeconds: 10